name: CI-master-nuget

on: 
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.100
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Build with dotnet
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        dotnet build --configuration Release ./IctBaden.Pixoo.sln -p:AssemblyVersion=$version -p:PackageVersion=$version -p:Version=1.0
    - name: Test with dotnet
      env: 
        SkipPerformanceTests: true
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        dotnet test ./IctBaden.Pixoo.sln --configuration Release -p:AssemblyVersion=$version -p:PackageVersion=$version -p:Version=1.0
    - name: Publish NuGet
      run: |
        version=$(grep -oP -m 1 '\* \K[0-9]*\.[0-9]*\.[0-9]*' ReleaseNotes.md)
        echo Version=$version
        dotnet nuget push IctBaden.Pixoo/bin/Release/*.nupkg --source https://www.nuget.org --api-key ${{ secrets.NugetKey }}
